pipeline:
  Build:
    image: alpine:latest
    commands:
      - echo "Test Message from agent"

  Publish:
    image: alpine:latest
    commands:
      - echo "Show env vars"
      - env
    secrets: [ docker_username, my_test, gold ]

  sonar:
    image: walmartdigital.azurecr.io/sonar-scanner-drone-plugin
    project_key: default:dronetest
    sources_directory: app
    environment:
      - SONAR_HOST=https://sonar.tools-aqchca.walmartdigital.cl
    secrets: [sonar_token]


  code_analisys:
    image: walmartdigital.azurecr.io/sonar-scanner-drone-plugin:latest
    project_key: sonar:pythontest
    sources_directory: python2.7
    environment:
      - SONAR_HOST=https://sonar.tools-aqchca.walmartdigital.cl

  # sonar:
  #   image: walmartdigital.azurecr.io/sonar-scanner-drone-plugin
  #   project_key: sonar:cstest
  #   sources_directory: cs
  #   environment:
  #     - SONAR_HOST=https://sonar.tools-aqchca.walmartdigital.cl

  # sonar_for_ex:
  #   image: walmartdigital.azurecr.io/sonar-scanner-drone-plugin
  #   project_key: sonar:elixirttest
  #   sources_directory: elixir
  #   environment:
  #     - SONAR_HOST=https://sonar.tools-aqchca.walmartdigital.cl